# Generated by Django 5.0 on 2023-12-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_rename_platform_watchlist_platform_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='platform_id',
            new_name='platform',
        ),
    ]
